"""task: snoozed_until separado de due_date

Revision ID: 4bb1e5778e0b
Revises: b2e1a4c7hnsw
Create Date: 2026-07-09 15:03:52.807034

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '4bb1e5778e0b'
down_revision = 'b2e1a4c7hnsw'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('snoozed_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'snoozed_until')
    # ### end Alembic commands ###
